# Generated by Django 3.1.7 on 2021-03-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rates_number', models.IntegerField(default=0)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company')),
            ],
        ),
    ]
