# Generated by Django 3.1.7 on 2021-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210327_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='make',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
