# Generated by Django 3.1.7 on 2021-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210327_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=3),
        ),
    ]
