# Generated by Django 3.1.7 on 2021-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210328_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car_id',
            new_name='car',
        ),
    ]
